/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSelfCheckRouteImport } from './routes/_app/self-check'
import { Route as AppSchoolRouteImport } from './routes/_app/school'
import { Route as AppSavedRouteImport } from './routes/_app/saved'
import { Route as AppQuizRouteImport } from './routes/_app/quiz'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppMotivationRouteImport } from './routes/_app/motivation'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppEmergencyRouteImport } from './routes/_app/emergency'
import { Route as AppEdukasiRouteImport } from './routes/_app/edukasi'
import { Route as AppDiaryRouteImport } from './routes/_app/diary'
import { Route as AppCommunityRouteImport } from './routes/_app/community'
import { Route as AppChallengeRouteImport } from './routes/_app/challenge'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppProfileSettingsRouteImport } from './routes/_app/profile.settings'
import { Route as AppProfilePrivacyRouteImport } from './routes/_app/profile.privacy'
import { Route as AppProfileEditRouteImport } from './routes/_app/profile.edit'
import { Route as AppEdukasiSlugRouteImport } from './routes/_app/edukasi.$slug'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSelfCheckRoute = AppSelfCheckRouteImport.update({
  id: '/self-check',
  path: '/self-check',
  getParentRoute: () => AppRoute,
} as any)
const AppSchoolRoute = AppSchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizRoute = AppQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMotivationRoute = AppMotivationRouteImport.update({
  id: '/motivation',
  path: '/motivation',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppEmergencyRoute = AppEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AppRoute,
} as any)
const AppEdukasiRoute = AppEdukasiRouteImport.update({
  id: '/edukasi',
  path: '/edukasi',
  getParentRoute: () => AppRoute,
} as any)
const AppDiaryRoute = AppDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppChallengeRoute = AppChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileSettingsRoute = AppProfileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppProfilePrivacyRoute = AppProfilePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppEdukasiSlugRoute = AppEdukasiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppEdukasiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/challenge': typeof AppChallengeRoute
  '/community': typeof AppCommunityRoute
  '/diary': typeof AppDiaryRoute
  '/edukasi': typeof AppEdukasiRouteWithChildren
  '/emergency': typeof AppEmergencyRoute
  '/home': typeof AppHomeRoute
  '/motivation': typeof AppMotivationRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/quiz': typeof AppQuizRoute
  '/saved': typeof AppSavedRoute
  '/school': typeof AppSchoolRoute
  '/self-check': typeof AppSelfCheckRoute
  '/edukasi/$slug': typeof AppEdukasiSlugRoute
  '/profile/edit': typeof AppProfileEditRoute
  '/profile/privacy': typeof AppProfilePrivacyRoute
  '/profile/settings': typeof AppProfileSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/challenge': typeof AppChallengeRoute
  '/community': typeof AppCommunityRoute
  '/diary': typeof AppDiaryRoute
  '/edukasi': typeof AppEdukasiRouteWithChildren
  '/emergency': typeof AppEmergencyRoute
  '/home': typeof AppHomeRoute
  '/motivation': typeof AppMotivationRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/quiz': typeof AppQuizRoute
  '/saved': typeof AppSavedRoute
  '/school': typeof AppSchoolRoute
  '/self-check': typeof AppSelfCheckRoute
  '/edukasi/$slug': typeof AppEdukasiSlugRoute
  '/profile/edit': typeof AppProfileEditRoute
  '/profile/privacy': typeof AppProfilePrivacyRoute
  '/profile/settings': typeof AppProfileSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/challenge': typeof AppChallengeRoute
  '/_app/community': typeof AppCommunityRoute
  '/_app/diary': typeof AppDiaryRoute
  '/_app/edukasi': typeof AppEdukasiRouteWithChildren
  '/_app/emergency': typeof AppEmergencyRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/motivation': typeof AppMotivationRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRouteWithChildren
  '/_app/quiz': typeof AppQuizRoute
  '/_app/saved': typeof AppSavedRoute
  '/_app/school': typeof AppSchoolRoute
  '/_app/self-check': typeof AppSelfCheckRoute
  '/_app/edukasi/$slug': typeof AppEdukasiSlugRoute
  '/_app/profile/edit': typeof AppProfileEditRoute
  '/_app/profile/privacy': typeof AppProfilePrivacyRoute
  '/_app/profile/settings': typeof AppProfileSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/admin'
    | '/challenge'
    | '/community'
    | '/diary'
    | '/edukasi'
    | '/emergency'
    | '/home'
    | '/motivation'
    | '/notifications'
    | '/profile'
    | '/quiz'
    | '/saved'
    | '/school'
    | '/self-check'
    | '/edukasi/$slug'
    | '/profile/edit'
    | '/profile/privacy'
    | '/profile/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/admin'
    | '/challenge'
    | '/community'
    | '/diary'
    | '/edukasi'
    | '/emergency'
    | '/home'
    | '/motivation'
    | '/notifications'
    | '/profile'
    | '/quiz'
    | '/saved'
    | '/school'
    | '/self-check'
    | '/edukasi/$slug'
    | '/profile/edit'
    | '/profile/privacy'
    | '/profile/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/_app/admin'
    | '/_app/challenge'
    | '/_app/community'
    | '/_app/diary'
    | '/_app/edukasi'
    | '/_app/emergency'
    | '/_app/home'
    | '/_app/motivation'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/quiz'
    | '/_app/saved'
    | '/_app/school'
    | '/_app/self-check'
    | '/_app/edukasi/$slug'
    | '/_app/profile/edit'
    | '/_app/profile/privacy'
    | '/_app/profile/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/self-check': {
      id: '/_app/self-check'
      path: '/self-check'
      fullPath: '/self-check'
      preLoaderRoute: typeof AppSelfCheckRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/school': {
      id: '/_app/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof AppSchoolRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved': {
      id: '/_app/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quiz': {
      id: '/_app/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AppQuizRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/motivation': {
      id: '/_app/motivation'
      path: '/motivation'
      fullPath: '/motivation'
      preLoaderRoute: typeof AppMotivationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/emergency': {
      id: '/_app/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof AppEmergencyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/edukasi': {
      id: '/_app/edukasi'
      path: '/edukasi'
      fullPath: '/edukasi'
      preLoaderRoute: typeof AppEdukasiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diary': {
      id: '/_app/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof AppDiaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/challenge': {
      id: '/_app/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof AppChallengeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/settings': {
      id: '/_app/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof AppProfileSettingsRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/profile/privacy': {
      id: '/_app/profile/privacy'
      path: '/privacy'
      fullPath: '/profile/privacy'
      preLoaderRoute: typeof AppProfilePrivacyRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/profile/edit': {
      id: '/_app/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/edukasi/$slug': {
      id: '/_app/edukasi/$slug'
      path: '/$slug'
      fullPath: '/edukasi/$slug'
      preLoaderRoute: typeof AppEdukasiSlugRouteImport
      parentRoute: typeof AppEdukasiRoute
    }
  }
}

interface AppEdukasiRouteChildren {
  AppEdukasiSlugRoute: typeof AppEdukasiSlugRoute
}

const AppEdukasiRouteChildren: AppEdukasiRouteChildren = {
  AppEdukasiSlugRoute: AppEdukasiSlugRoute,
}

const AppEdukasiRouteWithChildren = AppEdukasiRoute._addFileChildren(
  AppEdukasiRouteChildren,
)

interface AppProfileRouteChildren {
  AppProfileEditRoute: typeof AppProfileEditRoute
  AppProfilePrivacyRoute: typeof AppProfilePrivacyRoute
  AppProfileSettingsRoute: typeof AppProfileSettingsRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileEditRoute: AppProfileEditRoute,
  AppProfilePrivacyRoute: AppProfilePrivacyRoute,
  AppProfileSettingsRoute: AppProfileSettingsRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppChallengeRoute: typeof AppChallengeRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppDiaryRoute: typeof AppDiaryRoute
  AppEdukasiRoute: typeof AppEdukasiRouteWithChildren
  AppEmergencyRoute: typeof AppEmergencyRoute
  AppHomeRoute: typeof AppHomeRoute
  AppMotivationRoute: typeof AppMotivationRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppQuizRoute: typeof AppQuizRoute
  AppSavedRoute: typeof AppSavedRoute
  AppSchoolRoute: typeof AppSchoolRoute
  AppSelfCheckRoute: typeof AppSelfCheckRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppChallengeRoute: AppChallengeRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppDiaryRoute: AppDiaryRoute,
  AppEdukasiRoute: AppEdukasiRouteWithChildren,
  AppEmergencyRoute: AppEmergencyRoute,
  AppHomeRoute: AppHomeRoute,
  AppMotivationRoute: AppMotivationRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppQuizRoute: AppQuizRoute,
  AppSavedRoute: AppSavedRoute,
  AppSchoolRoute: AppSchoolRoute,
  AppSelfCheckRoute: AppSelfCheckRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
